name: Package

on:
  push:
    branches: [ main ]

jobs:

  Build:

    name: Build
    runs-on: windows-2019
    if: "contains(github.event.head_commit.message, '+ PACKAGE')"

    steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v2
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v4.3'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          python setup.py install

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: './F95Checker'

      - name: Build
        run: |
          cd .\F95Checker
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec

      - name: Cleanup + Include .py files
        shell: cmd
        run: |
          cd      .\F95Checker
          del  /f dist\windows\F95Checker\Qt5WebSockets.dll
          del  /f dist\windows\F95Checker\Qt5Svg.dll
          del  /f dist\windows\F95Checker\Qt5Quick.dll
          del  /f dist\windows\F95Checker\Qt5QmlModels.dll
          del  /f dist\windows\F95Checker\Qt5Qml.dll
          del  /f dist\windows\F95Checker\Qt5Network.dll
          del  /f dist\windows\F95Checker\Qt5DBus.dll
          mkdir   dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\aiohttp                                   dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\multidict                                 dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\tcl8                                      dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\yarl                                      dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_asyncio.pyd                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_ctypes.pyd                               dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_hashlib.pyd                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_overlapped.pyd                           dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_queue.pyd                                dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_socket.pyd                               dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_ssl.pyd                                  dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_tkinter.pyd                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_uuid.pyd                                 dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\_win32sysloader.pyd                       dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\api-ms-win-*                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\d3dcompiler_47.dll                        dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libcrypto-1_1.dll                         dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libEGL.dll                                dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libffi-7.dll                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libGLESv2.dll                             dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libssl-1_1.dll                            dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\MSVCP140_1.dll                            dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\MSVCP140.dll                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\opengl32sw.dll                            dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\select.pyd                                dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\tcl86t.dll                                dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\tk86t.dll                                 dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\ucrtbase.dll                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\unicodedata.pyd                           dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\VCRUNTIME140_1.dll                        dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\VCRUNTIME140.dll                          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\win32api.pyd                              dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\win32event.pyd                            dist\windows\F95Checker\lib
          mkdir   dist\windows\F95Checker\modules
          copy /y F95Checker.py                                                     dist\windows\F95Checker
          copy /y F95Checker.sh                                                     dist\windows\F95Checker
          copy /y requirements_linux.txt                                            dist\windows\F95Checker
          copy /y requirements.txt                                                  dist\windows\F95Checker
          copy /y update.py                                                         dist\windows\F95Checker
          copy /y update.exe                                                        dist\windows\F95Checker
          copy /y modules                                                           dist\windows\F95Checker\modules

      - name: Get short SHA string
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Zip package
        shell: cmd
        run: 7z a -r .\F95Checker-${{ steps.short-sha.outputs.sha }}.zip .\F95Checker\dist\windows\F95Checker\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: F95Checker-${{ steps.short-sha.outputs.sha }}
          path: ./F95Checker-${{ steps.short-sha.outputs.sha }}.zip

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
