name: Build Release Binaries

on:
  release:
    types: [created]

jobs:

  Build:

    name: Build
    runs-on: ubuntu-20.04

    steps:

      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Build Application
        uses: Willy-JL/pyinstaller-action-windows@main
        with:
          path: ./

      - name: Remove redundant libs
        run: rm -rf dist/windows/F95Checker/Include dist/windows/F95Checker/api-ms-win-* dist/windows/F95Checker/Qt5WebSockets.dll dist/windows/F95Checker/Qt5Svg.dll dist/windows/F95Checker/Qt5Quick.dll dist/windows/F95Checker/Qt5QmlModels.dll dist/windows/F95Checker/Qt5Qml.dll dist/windows/F95Checker/Qt5Network.dll dist/windows/F95Checker/Qt5DBus.dll dist/windows/F95Checker/ucrtbase.dll

      - name: Move libs to lib dir
        run: mkdir dist/windows/F95Checker/lib && mv dist/windows/F95Checker/aiohttp dist/windows/F95Checker/lib && mv dist/windows/F95Checker/multidict dist/windows/F95Checker/lib && mv dist/windows/F95Checker/tcl8 dist/windows/F95Checker/lib && mv dist/windows/F95Checker/yarl dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_asyncio.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_ctypes.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_hashlib.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_overlapped.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_queue.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_socket.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_ssl.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/_tkinter.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/d3dcompiler_47.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/libcrypto-1_1.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/libEGL.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/libffi-7.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/libGLESv2.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/libssl-1_1.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/MSVCP140.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/MSVCP140_1.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/opengl32sw.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/python3.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/select.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/tcl86t.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/tk86t.dll dist/windows/F95Checker/lib && mv dist/windows/F95Checker/unicodedata.pyd dist/windows/F95Checker/lib && mv dist/windows/F95Checker/VCRUNTIME140.dll dist/windows/F95Checker/lib

      - name: Move python files to dist folder
        run: mv F95Checker.py dist/windows/F95Checker && mv F95Checker.sh dist/windows/F95Checker && mv requirements.txt dist/windows/F95Checker && mv update.py dist/windows/F95Checker && mv update.exe dist/windows/F95Checker && mv modules dist/windows/F95Checker

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0

      - name: Delete skipped workflow runs
        uses: Willy-JL/delete-skipped-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0

      - name: Zip Binaries
        uses: papeloto/action-zip@v1
        with:
          files: dist/windows/F95Checker/*
          dest: F95CheckerV$GITHUB_REF.zip

      - name: Upload Binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'F95CheckerV*.zip'
